sudo: required
language: java
jdk: oraclejdk8
dist: trusty
os:
  - linux
git:
  depth: false
  submodules: false

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 9166c3b5-d71b-4714-95aa-3fd6811d59dc
